removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;

this forceAddUniform "U_B_CombatUniform_mcam";
this addVest "V_PlateCarrierGL_rgr";
for "_i" from 1 to 3 do {this addItemToVest "11Rnd_45ACP_Mag";};
for "_i" from 1 to 6 do {this addItemToVest "30Rnd_65x39_caseless_mag_Tracer";};
for "_i" from 1 to 6 do {this addItemToVest "1Rnd_HE_Grenade_shell";};
for "_i" from 1 to 2 do {this addItemToVest "UGL_FlareCIR_F";};
for "_i" from 1 to 2 do {this addItemToVest "UGL_FlareGreen_F";};
for "_i" from 1 to 2 do {this addItemToVest "1Rnd_SmokeGreen_Grenade_shell";};
this addBackpack "B_AssaultPack_Kerry";
for "_i" from 1 to 2 do {this addItemToBackpack "11Rnd_45ACP_Mag";};
this addItemToBackpack "1Rnd_HE_Grenade_shell";
this addHeadgear "H_HelmetSpecB_paint1";
this addGoggles "G_Tactical_Clear";
this addWeapon "arifle_MX_GL_F";
this addPrimaryWeaponItem "acc_pointer_IR";
this addPrimaryWeaponItem "optic_Hamr";
this addWeapon "hgun_Pistol_heavy_01_F";
this addHandgunItem "optic_MRD";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemRadio";
this linkItem "ItemGPS";
this linkItem "NVGoggles";