removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;

this forceAddUniform "U_B_CombatUniform_mcam_tshirt";
this addItemToUniform "FirstAidKit";
this addItemToUniform "11Rnd_45ACP_Mag";
this addItemToUniform "MiniGrenade";
this addVest "V_PlateCarrierGL_rgr";
for "_i" from 1 to 2 do {this addItemToVest "FirstAidKit";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShellGreen";};
for "_i" from 1 to 2 do {this addItemToVest "Chemlight_green";};
for "_i" from 1 to 2 do {this addItemToVest "11Rnd_45ACP_Mag";};
this addBackpack "B_Kitbag_rgr";
for "_i" from 1 to 2 do {this addItemToBackpack "FirstAidKit";};
for "_i" from 1 to 4 do {this addItemToBackpack "200Rnd_65x39_cased_Box";};
for "_i" from 1 to 2 do {this addItemToBackpack "HandGrenade";};
for "_i" from 1 to 5 do {this addItemToBackpack "SmokeShell";};
for "_i" from 1 to 4 do {this addItemToBackpack "Chemlight_green";};
this addHeadgear "H_HelmetB_light_grass";
this addWeapon "LMG_Mk200_F";
this addPrimaryWeaponItem "acc_pointer_IR";
this addPrimaryWeaponItem "optic_Hamr";
this addPrimaryWeaponItem "bipod_01_F_blk";
this addWeapon "hgun_Pistol_heavy_01_F";
this addHandgunItem "optic_MRD";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemRadio";
this linkItem "ItemGPS";
this linkItem "NVGoggles";