removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;

this forceAddUniform "U_B_CombatUniform_mcam";
for "_i" from 1 to 3 do {this addItemToUniform "30Rnd_65x39_caseless_mag";};
this addVest "V_PlateCarrierGL_blk";
this addBackpack "B_Kitbag_cbr";
for "_i" from 1 to 5 do {this addItemToBackpack "FirstAidKit";};
this addItemToBackpack "Medikit";
for "_i" from 1 to 2 do {this addItemToBackpack "11Rnd_45ACP_Mag";};
for "_i" from 1 to 7 do {this addItemToBackpack "30Rnd_65x39_caseless_mag";};
for "_i" from 1 to 2 do {this addItemToBackpack "HandGrenade";};
this addHeadgear "H_Cap_usblack";
this addWeapon "arifle_MX_GL_Black_F";
this addPrimaryWeaponItem "acc_pointer_IR";
this addPrimaryWeaponItem "optic_Holosight_smg";
this addWeapon "hgun_Pistol_heavy_01_F";
this addHandgunItem "optic_MRD";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemRadio";
this linkItem "ItemGPS";
